version: '3'

services:
  tuic:
    image: ghcr.io/zenithiks/tuic:latest
    restart: always
    network_mode: "host"
    environment:
      - USERS=00000000-0000-0000-0000-000000000000:PASSWORD_0,00000000-0000-0000-0000-000000000001:PASSWORD_1 # 改为自己的UUID:PASSWORD
      - CONGESTION_CONTROLLER=bbr
      - UDP_RELAY_IPV6=true
      - ZERO_RTT_HANDSHAKE=false
      - DUAL_STACK=true
    volumes:
      - /root/fullchain.pem:/opt/tuic/fullchain.pem:ro
      - /root/private.pem:/opt/tuic/private.pem:ro
  # ss:
  #   image: ghcr.io/zenithiks/ss:latest
  #   restart: always
  #   network_mode: "host"
  #   environment:
  #     - SERVER=::0
  #     - SERVER_PORT=8388
  #     - PASSWORD=xxx # 改为自己的密码
  #     - METHOD=chacha20-ietf-poly1305
  snell:
    image: ghcr.io/zenithiks/snell:latest
    restart: always
    network_mode: "host"
    environment:
      - LISTEN=:::8388
      - PSK=xxx # 改为自己的密码
      - IPV6=true # 不要 IPV6 可以改为 false 或者直接删掉这一行
  stls:
    image: ghcr.io/ihciah/shadow-tls:latest
    restart: always
    network_mode: "host"
    environment:
      - MODE=server
      - LISTEN=[::]:443
      - SERVER=127.0.0.1:8388 # 跟 snell/ss 监听的端口一致
      - TLS=captive.apple.com:443;cloud.tencent.com:443
      - PASSWORD=xxx # 改为自己的密码
      - ALPN=h2
      - DISABLE_NODELAY=0
      - FASTOPEN=1
      - V3=1
      - STRICT=1
      - WILDCARD_SNI=authed
